### PR TITLE
Add flycheck-checkbashisms to extensions list

### PR DESCRIPTION
**Pull request by Gnouc**
I wrote [`flycheck-checkbashisms`](https://github.com/Gnouc/flycheck-checkbashisms), another linter for shell script using `checkbashisms`.

This pull request add [`flycheck-checkbashisms`](https://github.com/Gnouc/flycheck-checkbashisms) to extensions package list, let our community notice about it.

Thanks.

### CODE REVIEW

**Comment by Gnouc** [comment]
@lunaryorn Not sure why my change can cause travis broken.

**Comment by lunaryorn** [comment]
@Gnouc Thank you.  The Travis failure is mine, never mind.  Would you mind to tell me what `checkbashisms` is and where it comes from?  I'd like to add a little more text to help users understand what this extension does :relaxed:

**Comment by Gnouc** [comment]
@lunaryorn [checkbashisms][checkbashisms-url] is part of Debian [devscript][devscript-url].

It performs basic checks on shell scripts for all possible presence of bashisms, i.e using array variable, `printf -v`, variable indirection `${!a}`. It can be combined with `shell-check` to prevent mistake when writing POSIX shell. Consider this:
```sh
#!/bin/sh

echo "${!a}"
echo "${!b}"
printf -v a 123
```
`shellcheck` silently accept it as a valid syntax, while it will fail when running. `checkbashisms` help us this case.

[checkbashisms-url]: https://anonscm.debian.org/cgit/collab-maint/devscripts.git/tree/scripts/checkbashisms.pl "checkbashisms"
[devscript-url]: https://anonscm.debian.org/cgit/collab-maint/devscripts.git "devscript"

**Comment by lunaryorn** [comment]
@Gnouc Thank you for these clarifications.

I have reviewed your extension, and found a couple of issues that I'd like to see solved before we can add your extension to our list of extensions.  See https://github.com/Gnouc/flycheck-checkbashisms/issues/2.

Please address these issues.  If you have any further questions, please don't hesitate to ask questions.  We'll help you address these issues, so that eventually your extension gets its place in our list :relaxed:

Thank you

**Comment by lunaryorn** [comment]
@Gnouc I've added your extension to our list.  Thank you for much for providing this great tool to our users and for your quick response to my concerns! :+1: :fireworks: :relaxed:

**Comment by Gnouc** [comment]
@lunaryorn You're welcome :+1:

**Pull request closed without merging**
